import React, { useState, useEffect, useMemo } from 'react';
import { Recipe, PantryItem, WeeklyPlan, ShoppingListItem, RecipeDiet, RecipeDifficulty, RecipeCategory } from './types';
import { INITIAL_RECIPES, INITIAL_PANTRY } from './data';
import { getRecipeMatchScore } from './utils';

// Modular Components
import RecipeDetail from './components/RecipeDetail';
import PantryManager from './components/PantryManager';
import WeeklyPlanner from './components/WeeklyPlanner';
import ShoppingListManager from './components/ShoppingListManager';
import ChefAIPanel from './components/ChefAIPanel';

// Icons
import {
  Search,
  Filter,
  Heart,
  Calendar,
  ShoppingBag,
  ShoppingCart,
  Sparkles,
  ChefHat,
  Clock,
  X,
  Plus,
  BookOpen,
  Utensils,
  Maximize2
} from 'lucide-react';

export default function App() {
  // Navigation space tab
  const [activeTab, setActiveTab] = useState<'recipes' | 'pantry' | 'planning' | 'shopping' | 'chef-ai'>('recipes');

  // Core App states with LocalStorage persistence
  const [recipes, setRecipes] = useState<Recipe[]>(() => {
    const saved = localStorage.getItem('receitas_items');
    return saved ? JSON.parse(saved) : INITIAL_RECIPES;
  });

  const [pantry, setPantry] = useState<PantryItem[]>(() => {
    const saved = localStorage.getItem('receitas_pantry');
    return saved ? JSON.parse(saved) : INITIAL_PANTRY;
  });

  const [weeklyPlan, setWeeklyPlan] = useState<WeeklyPlan[]>(() => {
    const saved = localStorage.getItem('receitas_plan');
    return saved ? JSON.parse(saved) : [];
  });

  const [shoppingList, setShoppingList] = useState<ShoppingListItem[]>(() => {
    const saved = localStorage.getItem('receitas_shopping');
    return saved ? JSON.parse(saved) : [];
  });

  const [favorites, setFavorites] = useState<string[]>(() => {
    const saved = localStorage.getItem('receitas_favorites');
    return saved ? JSON.parse(saved) : [];
  });

  // Selected recipe for detail modal / view
  const [selectedRecipe, setSelectedRecipe] = useState<Recipe | null>(null);

  // Search & filter states for recipe library
  const [searchQuery, setSearchQuery] = useState('');
  const [dietFilter, setDietFilter] = useState<RecipeDiet | 'Todos'>('Todos');
  const [difficultyFilter, setDifficultyFilter] = useState<RecipeDifficulty | 'Todos'>('Todos');
  const [categoryFilter, setCategoryFilter] = useState<RecipeCategory | 'Todos'>('Todos');
  const [showOnlyFavorites, setShowOnlyFavorites] = useState(false);

  // Persist states to LocalStorage on changes
  useEffect(() => {
    localStorage.setItem('receitas_items', JSON.stringify(recipes));
  }, [recipes]);

  useEffect(() => {
    localStorage.setItem('receitas_pantry', JSON.stringify(pantry));
  }, [pantry]);

  useEffect(() => {
    localStorage.setItem('receitas_plan', JSON.stringify(weeklyPlan));
  }, [weeklyPlan]);

  useEffect(() => {
    localStorage.setItem('receitas_shopping', JSON.stringify(shoppingList));
  }, [shoppingList]);

  useEffect(() => {
    localStorage.setItem('receitas_favorites', JSON.stringify(favorites));
  }, [favorites]);

  // Toggle favorite recipe state
  const handleToggleFavorite = (recipeId: string) => {
    setFavorites(prev => {
      if (prev.includes(recipeId)) {
        return prev.filter(id => id !== recipeId);
      } else {
        return [...prev, recipeId];
      }
    });
  };

  // Add item directly to shopping list
  const handleAddShoppingListItem = (item: Omit<ShoppingListItem, 'id' | 'checked'>) => {
    const newItem: ShoppingListItem = {
      ...item,
      id: `shop-${Date.now()}-${Math.random().toString(36).substr(2, 4)}`,
      checked: false
    };
    setShoppingList(prev => [...prev, newItem]);
  };

  // Handle recipe generated by Chef AI
  const handleRecipeGenerated = (newRecipe: Recipe) => {
    setRecipes(prev => [newRecipe, ...prev]);
    setSelectedRecipe(newRecipe);
    setActiveTab('recipes'); // switch back to library to view it
  };

  // Filter recipes based on query, diet, difficulty, category, and favorites toggles
  const filteredRecipes = useMemo(() => {
    return recipes.filter(recipe => {
      // Search matches title or ingredients
      const matchesSearch = 
        recipe.title.toLowerCase().includes(searchQuery.toLowerCase()) ||
        recipe.description.toLowerCase().includes(searchQuery.toLowerCase()) ||
        recipe.ingredients.some(ing => ing.name.toLowerCase().includes(searchQuery.toLowerCase()));

      const matchesDiet = dietFilter === 'Todos' || recipe.diet === dietFilter;
      const matchesDifficulty = difficultyFilter === 'Todos' || recipe.difficulty === difficultyFilter;
      const matchesCategory = categoryFilter === 'Todos' || recipe.category === categoryFilter;
      const matchesFavorite = !showOnlyFavorites || favorites.includes(recipe.id);

      return matchesSearch && matchesDiet && matchesDifficulty && matchesCategory && matchesFavorite;
    });
  }, [recipes, searchQuery, dietFilter, difficultyFilter, categoryFilter, showOnlyFavorites, favorites]);

  // Calculate missing stock info for filtered recipes to showcase live inventory matches
  const recipesWithStockInfo = useMemo(() => {
    return filteredRecipes.map(recipe => {
      const match = getRecipeMatchScore(recipe, pantry);
      return {
        recipe,
        percentage: match.percentage,
        available: match.availableCount,
        total: match.totalCount
      };
    });
  }, [filteredRecipes, pantry]);

  // Count items running out in pantry for header badge alerts
  const lowStockPantryCount = useMemo(() => {
    return pantry.filter(item => item.quantity <= item.minQuantity).length;
  }, [pantry]);

  // Count active unchecked shopping list items
  const activeShoppingCount = useMemo(() => {
    return shoppingList.filter(item => !item.checked).length;
  }, [shoppingList]);

  return (
    <div className="min-h-screen bg-slate-50 flex flex-col font-sans">
      
      {/* Visual Elegant Header with Navigation spaces */}
      <header className="sticky top-0 z-40 bg-white/90 backdrop-blur-md border-b border-slate-100">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex justify-between items-center h-16 sm:h-20">
            
            {/* Elegant brand typography and humble description */}
            <div className="flex items-center gap-4 cursor-pointer" onClick={() => { setSelectedRecipe(null); setActiveTab('recipes'); }}>
              <div className="w-10 h-10 bg-orange-500 rounded-full flex items-center justify-center text-white">
                <ChefHat size={20} className="stroke-2" />
              </div>
              <div>
                <h1 className="text-2xl font-serif italic font-bold tracking-tight text-slate-800 leading-none">
                  Cozinha Inteligente
                </h1>
                <span className="text-[10px] text-slate-400 font-medium tracking-widest uppercase mt-1.5 block">
                  Receitas & Planejamento
                </span>
              </div>
            </div>

            {/* Desktop Navigation Spaces */}
            <nav className="hidden lg:flex gap-8 text-xs font-semibold uppercase tracking-widest">
              <button
                onClick={() => { setSelectedRecipe(null); setActiveTab('recipes'); }}
                className={`pb-1 transition-all cursor-pointer ${
                  activeTab === 'recipes'
                    ? 'text-orange-500 border-b-2 border-orange-500 font-bold'
                    : 'text-slate-400 hover:text-slate-800'
                }`}
              >
                <span>Receitas</span>
              </button>

              <button
                onClick={() => { setSelectedRecipe(null); setActiveTab('pantry'); }}
                className={`pb-1 transition-all relative cursor-pointer ${
                  activeTab === 'pantry'
                    ? 'text-orange-500 border-b-2 border-orange-500 font-bold'
                    : 'text-slate-400 hover:text-slate-800'
                }`}
              >
                <span>Despensa</span>
                {lowStockPantryCount > 0 && (
                  <span className="absolute -top-1.5 -right-3.5 w-4 h-4 rounded-full bg-amber-500 text-white text-[9px] font-bold flex items-center justify-center">
                    {lowStockPantryCount}
                  </span>
                )}
              </button>

              <button
                onClick={() => { setSelectedRecipe(null); setActiveTab('planning'); }}
                className={`pb-1 transition-all cursor-pointer ${
                  activeTab === 'planning'
                    ? 'text-orange-500 border-b-2 border-orange-500 font-bold'
                    : 'text-slate-400 hover:text-slate-800'
                }`}
              >
                <span>Planejamento</span>
              </button>

              <button
                onClick={() => { setSelectedRecipe(null); setActiveTab('shopping'); }}
                className={`pb-1 transition-all relative cursor-pointer ${
                  activeTab === 'shopping'
                    ? 'text-orange-500 border-b-2 border-orange-500 font-bold'
                    : 'text-slate-400 hover:text-slate-800'
                }`}
              >
                <span>Lista de Compras</span>
                {activeShoppingCount > 0 && (
                  <span className="absolute -top-1.5 -right-3.5 w-4 h-4 rounded-full bg-rose-500 text-white text-[9px] font-bold flex items-center justify-center animate-pulse">
                    {activeShoppingCount}
                  </span>
                )}
              </button>

              <button
                onClick={() => { setSelectedRecipe(null); setActiveTab('chef-ai'); }}
                className={`pb-1 transition-all cursor-pointer ${
                  activeTab === 'chef-ai'
                    ? 'text-orange-500 border-b-2 border-orange-500 font-bold'
                    : 'text-orange-500/70 hover:text-orange-500'
                }`}
              >
                <span>Chef IA ✦</span>
              </button>
            </nav>

            {/* Basic Mobile layout indicators */}
            <div className="flex lg:hidden items-center gap-1">
              <button
                onClick={() => { setSelectedRecipe(null); setActiveTab('chef-ai'); }}
                className={`p-2 rounded-xl transition-all ${
                  activeTab === 'chef-ai' ? 'bg-purple-50 text-purple-600' : 'text-purple-600'
                }`}
                title="Chef IA"
              >
                <Sparkles size={18} className="text-yellow-500 fill-yellow-400" />
              </button>
            </div>

          </div>
        </div>
      </header>

      {/* Main layout container */}
      <main className="flex-1 max-w-7xl w-full mx-auto px-4 sm:px-6 lg:px-8 py-6 sm:py-8">
        
        {/* Render a single recipe detailed view if selected */}
        {selectedRecipe ? (
          <RecipeDetail
            recipe={selectedRecipe}
            pantry={pantry}
            isFavorite={favorites.includes(selectedRecipe.id)}
            onToggleFavorite={() => handleToggleFavorite(selectedRecipe.id)}
            onAddToShoppingList={handleAddShoppingListItem}
            onClose={() => setSelectedRecipe(null)}
          />
        ) : (
          <>
            {/* 1. Recipe Catalog Space */}
            {activeTab === 'recipes' && (
              <div className="space-y-6">
                
                {/* Advanced Search & Filtering Controls */}
                <div className="bg-white p-5 sm:p-6 rounded-2xl border border-slate-100 shadow-sm space-y-4">
                  
                  {/* Text search */}
                  <div className="relative">
                    <Search className="absolute left-3.5 top-3.5 text-slate-400" size={18} />
                    <input
                      type="text"
                      placeholder="Buscar por nome de receita ou ingrediente (Ex: salmão, aveia...)"
                      value={searchQuery}
                      onChange={e => setSearchQuery(e.target.value)}
                      className="w-full pl-11 pr-4 py-3 rounded-xl border border-slate-200 text-sm focus:outline-none focus:ring-2 focus:ring-orange-500/20 focus:border-orange-500 transition-all font-medium"
                    />
                    {searchQuery && (
                      <button
                        onClick={() => setSearchQuery('')}
                        className="absolute right-3 top-3.5 text-slate-400 hover:text-slate-600"
                      >
                        <X size={16} />
                      </button>
                    )}
                  </div>

                  {/* Filter chips container */}
                  <div className="flex flex-wrap gap-4 items-center justify-between pt-1">
                    <div className="flex flex-wrap gap-2.5 items-center">
                      
                      {/* Diet filter */}
                      <div className="flex items-center gap-1 bg-slate-50 rounded-xl p-1 border border-slate-100">
                        <span className="text-[10px] text-slate-400 uppercase font-bold tracking-wider px-2">Dieta</span>
                        {['Todos', 'Fit', 'Fim de Semana', 'Calórica'].map(d => (
                          <button
                            key={d}
                            onClick={() => setDietFilter(d as any)}
                            className={`px-2.5 py-1 text-xs font-semibold rounded-lg transition-all ${
                              dietFilter === d
                                ? 'bg-white text-slate-800 shadow-sm'
                                : 'text-slate-500 hover:text-slate-800'
                            }`}
                          >
                            {d}
                          </button>
                        ))}
                      </div>

                      {/* Difficulty filter */}
                      <div className="flex items-center gap-1 bg-slate-50 rounded-xl p-1 border border-slate-100">
                        <span className="text-[10px] text-slate-400 uppercase font-bold tracking-wider px-2">Complexidade</span>
                        {['Todos', 'Fácil', 'Médio', 'Difícil'].map(dif => (
                          <button
                            key={dif}
                            onClick={() => setDifficultyFilter(dif as any)}
                            className={`px-2.5 py-1 text-xs font-semibold rounded-lg transition-all ${
                              difficultyFilter === dif
                                ? 'bg-white text-slate-800 shadow-sm'
                                : 'text-slate-500 hover:text-slate-800'
                            }`}
                          >
                            {dif}
                          </button>
                        ))}
                      </div>

                      {/* Meal occasions filter */}
                      <div className="flex items-center gap-1 bg-slate-50 rounded-xl p-1 border border-slate-100">
                        <span className="text-[10px] text-slate-400 uppercase font-bold tracking-wider px-2">Ocasião</span>
                        {['Todos', 'Dia a Dia', 'Domingo'].map(cat => (
                          <button
                            key={cat}
                            onClick={() => setCategoryFilter(cat as any)}
                            className={`px-2.5 py-1 text-xs font-semibold rounded-lg transition-all ${
                              categoryFilter === cat
                                ? 'bg-white text-slate-800 shadow-sm'
                                : 'text-slate-500 hover:text-slate-800'
                            }`}
                          >
                            {cat}
                          </button>
                        ))}
                      </div>

                    </div>

                    {/* Favorites Toggle */}
                    <button
                      onClick={() => setShowOnlyFavorites(!showOnlyFavorites)}
                      className={`px-3 py-1.5 rounded-xl text-xs font-semibold flex items-center gap-1.5 border transition-all ${
                        showOnlyFavorites
                          ? 'border-rose-200 bg-rose-50 text-rose-700'
                          : 'border-slate-200 hover:border-slate-300 text-slate-600'
                      }`}
                    >
                      <Heart size={14} fill={showOnlyFavorites ? '#e11d48' : 'none'} className={showOnlyFavorites ? 'text-rose-600' : 'text-slate-400'} />
                      <span>Favoritos</span>
                    </button>
                  </div>

                </div>

                {/* Recipe grid list with stock percentages */}
                {recipesWithStockInfo.length === 0 ? (
                  <div className="text-center py-20 bg-white rounded-2xl border border-slate-100">
                    <p className="text-slate-500 font-medium">Nenhuma receita encontrada com os filtros selecionados.</p>
                    <button
                      onClick={() => {
                        setSearchQuery('');
                        setDietFilter('Todos');
                        setDifficultyFilter('Todos');
                        setCategoryFilter('Todos');
                        setShowOnlyFavorites(false);
                      }}
                      className="text-xs text-orange-500 hover:underline mt-2 font-semibold"
                    >
                      Redefinir filtros de busca
                    </button>
                  </div>
                ) : (
                  <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
                    {recipesWithStockInfo.map(({ recipe, percentage, available, total }) => {
                      const isFav = favorites.includes(recipe.id);

                      return (
                        <div
                          key={recipe.id}
                          className="group bg-white rounded-2xl border border-slate-100 shadow-sm hover:shadow-md transition-all overflow-hidden flex flex-col justify-between"
                        >
                          {/* Recipe image banner */}
                          <div className="relative h-48 w-full bg-slate-100 overflow-hidden">
                            <img
                              src={recipe.image}
                              alt={recipe.title}
                              referrerPolicy="no-referrer"
                              className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-300 cursor-pointer"
                              onClick={() => setSelectedRecipe(recipe)}
                            />
                            
                            {/* Tags overlays */}
                            <div className="absolute top-3 left-3 flex flex-col gap-1">
                              <span className="px-2 py-0.5 text-[9px] font-bold tracking-wider uppercase rounded-md bg-white/95 text-slate-800 shadow">
                                {recipe.diet}
                              </span>
                              <span className="px-2 py-0.5 text-[9px] font-bold tracking-wider uppercase rounded-md bg-orange-500 text-white shadow">
                                {recipe.difficulty}
                              </span>
                            </div>

                            {/* Favorites toggler */}
                            <button
                              onClick={() => handleToggleFavorite(recipe.id)}
                              className="absolute top-3 right-3 p-1.5 rounded-full bg-white/90 hover:bg-white text-rose-500 shadow transition-all"
                            >
                              <Heart size={14} fill={isFav ? '#f43f5e' : 'none'} />
                            </button>

                            {/* Chef AI label */}
                            {recipe.isChefAI && (
                              <span className="absolute bottom-3 left-3 px-2 py-0.5 text-[9px] font-bold tracking-wider uppercase rounded-md bg-purple-600 text-white shadow-md">
                                ✦ Chef IA
                              </span>
                            )}
                          </div>

                          {/* Info area */}
                          <div className="p-5 flex-1 flex flex-col justify-between space-y-4">
                            <div className="space-y-1.5">
                              <h3
                                onClick={() => setSelectedRecipe(recipe)}
                                className="font-serif italic font-bold text-slate-800 text-lg leading-snug hover:text-orange-500 cursor-pointer line-clamp-1"
                              >
                                {recipe.title}
                              </h3>
                              <p className="text-xs text-slate-400 font-light line-clamp-2 leading-relaxed">
                                {recipe.description}
                              </p>
                            </div>

                            {/* Stock match indicator footer */}
                            <div className="pt-3 border-t border-slate-50 flex items-center justify-between">
                              <div className="flex flex-col">
                                <span className="text-[10px] text-slate-400 font-medium">Ingredientes em estoque</span>
                                <div className="flex items-center gap-1.5 mt-0.5">
                                  <div className="w-16 h-1.5 bg-slate-100 rounded-full overflow-hidden">
                                    <div
                                      className={`h-full rounded-full ${
                                        percentage === 100
                                          ? 'bg-emerald-500'
                                          : percentage >= 50
                                          ? 'bg-amber-500'
                                          : 'bg-rose-400'
                                      }`}
                                      style={{ width: `${percentage}%` }}
                                    ></div>
                                  </div>
                                  <span className="text-[10px] font-mono font-bold text-slate-600">
                                    {available}/{total}
                                  </span>
                                </div>
                              </div>

                              <button
                                onClick={() => setSelectedRecipe(recipe)}
                                className="text-xs text-slate-900 hover:text-orange-500 font-semibold flex items-center gap-0.5"
                              >
                                <span>Preparar</span>
                                <Maximize2 size={10} />
                              </button>
                            </div>
                          </div>

                        </div>
                      );
                    })}
                  </div>
                )}
              </div>
            )}

            {/* 2. Pantry Space */}
            {activeTab === 'pantry' && (
              <PantryManager
                pantry={pantry}
                recipes={recipes}
                onUpdatePantry={setPantry}
                onAddShoppingListItem={handleAddShoppingListItem}
                onSelectRecipe={setSelectedRecipe}
              />
            )}

            {/* 3. Family Planning space */}
            {activeTab === 'planning' && (
              <WeeklyPlanner
                weeklyPlan={weeklyPlan}
                recipes={recipes}
                onUpdatePlan={setWeeklyPlan}
                onAddShoppingListItem={handleAddShoppingListItem}
                onSelectRecipe={setSelectedRecipe}
              />
            )}

            {/* 4. Smart Shopping List space */}
            {activeTab === 'shopping' && (
              <ShoppingListManager
                shoppingList={shoppingList}
                onUpdateList={setShoppingList}
              />
            )}

            {/* 5. Chef AI Generation space */}
            {activeTab === 'chef-ai' && (
              <ChefAIPanel
                pantry={pantry}
                onRecipeGenerated={handleRecipeGenerated}
              />
            )}
          </>
        )}

      </main>

      {/* Footer component */}
      <footer className="bg-white border-t border-slate-100 py-6 mt-12 text-center text-xs text-slate-400">
        <div className="max-w-7xl mx-auto px-4">
          <p>© 2026 Cozinha Inteligente. Planejamento familiar com amor e inteligência artificial.</p>
        </div>
      </footer>

      {/* Tab bar for mobile screens (fixed to bottom) */}
      <div className="lg:hidden fixed bottom-0 left-0 right-0 bg-white border-t border-slate-100 py-2 px-3 flex justify-around items-center z-40 shadow-xl">
        <button
          onClick={() => { setSelectedRecipe(null); setActiveTab('recipes'); }}
          className={`flex flex-col items-center gap-0.5 ${activeTab === 'recipes' ? 'text-orange-500' : 'text-slate-400'}`}
        >
          <BookOpen size={18} />
          <span className="text-[9px] font-medium">Receitas</span>
        </button>

        <button
          onClick={() => { setSelectedRecipe(null); setActiveTab('pantry'); }}
          className={`flex flex-col items-center gap-0.5 relative ${activeTab === 'pantry' ? 'text-orange-500' : 'text-slate-400'}`}
        >
          <ShoppingBag size={18} />
          <span className="text-[9px] font-medium font-sans">Despensa</span>
          {lowStockPantryCount > 0 && (
            <span className="absolute top-0 right-2 w-2 h-2 rounded-full bg-amber-500"></span>
          )}
        </button>

        <button
          onClick={() => { setSelectedRecipe(null); setActiveTab('planning'); }}
          className={`flex flex-col items-center gap-0.5 ${activeTab === 'planning' ? 'text-orange-500' : 'text-slate-400'}`}
        >
          <Calendar size={18} />
          <span className="text-[9px] font-medium">Menu</span>
        </button>

        <button
          onClick={() => { setSelectedRecipe(null); setActiveTab('shopping'); }}
          className={`flex flex-col items-center gap-0.5 relative ${activeTab === 'shopping' ? 'text-orange-500' : 'text-slate-400'}`}
        >
          <ShoppingCart size={18} />
          <span className="text-[9px] font-medium">Compras</span>
          {activeShoppingCount > 0 && (
            <span className="absolute top-0 right-2 w-2 h-2 rounded-full bg-rose-500 animate-pulse"></span>
          )}
        </button>
      </div>

    </div>
  );
}
